# Generated by Django 5.1.5 on 2026-01-21 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('clothes_id', models.AutoField(db_column='clothes_id', primary_key=True, serialize=False)),
                ('f_user_uid', models.CharField(db_column='f_user_uid', max_length=255)),
                ('clothes_uid', models.CharField(db_column='clothes_uid', default=uuid.uuid4, max_length=255, unique=True)),
                ('clothes_category', models.CharField(db_column='clothes_category', max_length=100)),
                ('clothes_size', models.CharField(db_column='clothes_size', max_length=10)),
                ('clothes_image_url', models.CharField(db_column='clothes_image_url', max_length=500)),
                ('clothes_favorite', models.BooleanField(db_column='clothes_favorite', default=False)),
                ('clothes_created_time', models.DateTimeField(auto_now_add=True, db_column='clothes_created_time')),
                ('clothes_updated_time', models.DateTimeField(auto_now=True, db_column='clothes_updated_time')),
            ],
            options={
                'verbose_name': '衣伺',
                'verbose_name_plural': '衣伺',
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(db_column='color_id', primary_key=True, serialize=False)),
                ('f_clothes_uid', models.CharField(db_column='f_clothes_uid', max_length=255)),
                ('color_uid', models.CharField(db_column='color_uid', default=uuid.uuid4, max_length=255, unique=True)),
                ('color_name', models.CharField(db_column='color_name', max_length=100)),
            ],
            options={
                'verbose_name': '顏色',
                'verbose_name_plural': '顏色',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(db_column='style_id', primary_key=True, serialize=False)),
                ('f_clothes_uid', models.CharField(db_column='f_clothes_uid', max_length=255)),
                ('style_uid', models.CharField(db_column='style_uid', default=uuid.uuid4, max_length=255, unique=True)),
                ('style_name', models.CharField(db_column='style_name', max_length=100)),
            ],
            options={
                'verbose_name': '風格',
                'verbose_name_plural': '風格',
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_uid', models.CharField(db_column='user_uid', default=uuid.uuid4, max_length=255, unique=True)),
                ('user_name', models.CharField(db_column='user_name', max_length=150, unique=True)),
                ('user_email', models.EmailField(db_column='user_email', max_length=254, unique=True)),
                ('user_password', models.CharField(db_column='user_password', max_length=255)),
                ('user_weight', models.IntegerField(blank=True, db_column='user_weight', null=True)),
                ('user_height', models.IntegerField(blank=True, db_column='user_height', null=True)),
                ('user_image_url', models.CharField(blank=True, db_column='user_image_url', max_length=500, null=True)),
                ('user_created_time', models.DateTimeField(auto_now_add=True, db_column='user_created_time')),
                ('user_updated_time', models.DateTimeField(auto_now=True, db_column='user_updated_time')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, db_table='user_groups', help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, db_table='user_permissions', help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
                'db_table': 'user',
            },
        ),
    ]
