# Generated by Django 6.0.1 on 2026-01-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='clothes_size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_arm_length',
            field=models.IntegerField(blank=True, db_column='clothes_arm_length', help_text='袖長(cm)', null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_leg_length',
            field=models.IntegerField(blank=True, db_column='clothes_leg_length', help_text='褲長(cm)', null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_shoulder_width',
            field=models.IntegerField(blank=True, db_column='clothes_shoulder_width', help_text='肩寬(cm)', null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='clothes_waistline',
            field=models.IntegerField(blank=True, db_column='clothes_waistline', help_text='腰圍(cm)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_arm_length',
            field=models.IntegerField(blank=True, db_column='user_arm_length', help_text='手臂長度(cm)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_leg_length',
            field=models.IntegerField(blank=True, db_column='user_leg_length', help_text='腿長(cm)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_shoulder_width',
            field=models.IntegerField(blank=True, db_column='user_shoulder_width', help_text='肩寬(cm)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_waistline',
            field=models.IntegerField(blank=True, db_column='user_waistline', help_text='腰圍(cm)', null=True),
        ),
    ]
