# Generated by Django 6.0.1 on 2026-01-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_clothes_clothes_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='clothes_arm_length',
            field=models.IntegerField(db_column='clothes_arm_length', default=0, help_text='袖長(cm)'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_leg_length',
            field=models.IntegerField(db_column='clothes_leg_length', default=0, help_text='褲長(cm)'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_shoulder_width',
            field=models.IntegerField(db_column='clothes_shoulder_width', default=0, help_text='肩寬(cm)'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_waistline',
            field=models.IntegerField(db_column='clothes_waistline', default=0, help_text='腰圍(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_arm_length',
            field=models.IntegerField(db_column='user_arm_length', default=0, help_text='手臂長度(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_height',
            field=models.IntegerField(db_column='user_height', default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(db_column='user_image_url', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_leg_length',
            field=models.IntegerField(db_column='user_leg_length', default=0, help_text='腿長(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_shoulder_width',
            field=models.IntegerField(db_column='user_shoulder_width', default=0, help_text='肩寬(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_waistline',
            field=models.IntegerField(db_column='user_waistline', default=0, help_text='腰圍(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_weight',
            field=models.IntegerField(db_column='user_weight', default=0),
        ),
    ]
