# Generated by Django 6.0.1 on 2026-03-27 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clothes_clothes_arm_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(db_column='photo_id', primary_key=True, serialize=False)),
                ('photo_uid', models.CharField(db_column='photo_uid', default=uuid.uuid4, max_length=255, unique=True)),
                ('f_user_uid', models.CharField(db_column='f_user_uid', max_length=255)),
                ('photo_url', models.CharField(db_column='photo_url', max_length=500)),
                ('photo_filename', models.CharField(db_column='photo_filename', max_length=255)),
                ('photo_file_size', models.IntegerField(db_column='photo_file_size', default=0, help_text='檔案大小(bytes)')),
                ('photo_content_type', models.CharField(db_column='photo_content_type', default='image/jpeg', max_length=50)),
                ('photo_uploaded_time', models.DateTimeField(auto_now_add=True, db_column='photo_uploaded_time')),
                ('photo_updated_time', models.DateTimeField(auto_now=True, db_column='photo_updated_time')),
            ],
            options={
                'verbose_name': '用戶照片',
                'verbose_name_plural': '用戶照片',
                'db_table': 'photo',
            },
        ),
    ]
