# Generated by Django 5.1.5 on 2026-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_photo'),
        ('combine', '0002_remove_virtualtryon_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
