# Generated by Django 6.0.1 on 2026-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clothes_original_image_url',
            field=models.CharField(blank=True, db_column='clothes_original_image_url', default='', help_text='原始衣服圖片URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clothes_image_url',
            field=models.CharField(db_column='clothes_image_url', help_text='去背後的衣服圖片URL', max_length=500),
        ),
    ]
