# Generated by Django 6.0.1 on 2026-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_clothes_clothes_original_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_original_image_url',
            field=models.CharField(db_column='user_original_image_url', default='', help_text='原始模特照片URL（給AI後端使用）', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(db_column='user_image_url', default='', help_text='処理後的模特照片URL（給前端顯示）', max_length=500),
        ),
    ]
