# Generated by Django 6.0.1 on 2026-03-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_user_original_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='colors',
            field=models.JSONField(blank=True, default=list, help_text='衣伺顏色列表'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='styles',
            field=models.JSONField(blank=True, default=list, help_text='衣伺風格列表'),
        ),
    ]
