# Generated by Django 6.0.1 on 2026-03-28 23:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, help_text='对话会话的唯一标识', primary_key=True, serialize=False, unique=True)),
                ('context', models.CharField(choices=[('outfit_recommendation', 'Outfit Recommendation'), ('style_advice', 'Style Advice'), ('general', 'General Question')], default='general', help_text='对话类型', max_length=25)),
                ('tags', models.JSONField(blank=True, default=list, help_text='对话标签')),
                ('message_count', models.IntegerField(default=0, help_text='对话信息数量')),
                ('total_tokens_used', models.IntegerField(default=0, help_text='总 Token 使用数')),
                ('is_active', models.BooleanField(default=True, help_text='对话是否进行中')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('ended_at', models.DateTimeField(blank=True, help_text='结束时间', null=True)),
                ('f_user_uid', models.ForeignKey(help_text='用户外键', on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 对话',
                'verbose_name_plural': 'AI 对话',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, help_text='信息的唯一标识', primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='角色：用户或助手', max_length=10)),
                ('content', models.TextField(help_text='信息内容')),
                ('recommended_clothes', models.JSONField(blank=True, default=list, help_text='推荐的衣伺列表')),
                ('input_tokens', models.IntegerField(default=0, help_text='输入 Token 数')),
                ('output_tokens', models.IntegerField(default=0, help_text='输出 Token 数')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('conversation', models.ForeignKey(help_text='所属对话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aichat_service.conversation')),
            ],
            options={
                'verbose_name': '聊天信息',
                'verbose_name_plural': '聊天信息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['f_user_uid', '-created_at'], name='aichat_serv_f_user__e27d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active'], name='aichat_serv_is_acti_9e3828_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='aichat_serv_convers_756d33_idx'),
        ),
    ]
