# Generated by Django 6.0.1 on 2026-03-28 01:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('outfit_id', models.AutoField(primary_key=True, serialize=False)),
                ('outfit_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('outfit_name', models.CharField(help_text='使用者自訂的穿搭名稱', max_length=100, verbose_name='穿搭名稱')),
                ('outfit_description', models.TextField(blank=True, help_text='穿搭的詳細說明', null=True, verbose_name='穿搭描述')),
                ('preview_image_url', models.URLField(blank=True, help_text='穿搭組合的預覽圖片（由虛擬試衣生成）', null=True, verbose_name='穿搭預覽圖 URL')),
                ('is_draft', models.BooleanField(default=False, help_text='True：草稿；False：已發佈', verbose_name='是否為草稿')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(help_text='建立此穿搭的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '穿搭組合',
                'verbose_name_plural': '穿搭組合',
                'db_table': 'outfit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('try_on_id', models.AutoField(primary_key=True, serialize=False)),
                ('try_on_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('accepted', '已保存'), ('rejected', '已拒絕'), ('error', '處理失敗')], default='pending', help_text='虛擬試衣的處理狀態', max_length=20, verbose_name='狀態')),
                ('clothes_list', models.JSONField(default=list, help_text='虛擬試衣包含的衣伺 UID 陣列', verbose_name='衣伺列表')),
                ('result_image_url', models.URLField(blank=True, help_text='AI 後端返回的虛擬試衣合成圖片 URL', null=True, verbose_name='虛擬試衣結果圖')),
                ('result_file_name', models.CharField(blank=True, help_text='AI 返回的結果檔案名稱', max_length=255, verbose_name='結果檔案名')),
                ('ai_response_data', models.JSONField(blank=True, default=dict, help_text='AI 後端返回的完整 JSON 數據', verbose_name='AI 回應數據')),
                ('ai_error_message', models.TextField(blank=True, help_text='如果 AI 處理失敗，記錄錯誤詳情', null=True, verbose_name='錯誤信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('ai_processed_at', models.DateTimeField(blank=True, help_text='AI 處理完成的時間', null=True, verbose_name='AI 完成時間')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='用戶確認保存的時間', null=True, verbose_name='確認時間')),
                ('outfit', models.ForeignKey(blank=True, help_text='用戶選擇的參考穿搭（可選）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='try_ons', to='combine.outfit', verbose_name='參考穿搭')),
                ('user', models.ForeignKey(help_text='進行虛擬試衣的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_try_ons', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
                ('user_photo', models.ForeignKey(blank=True, help_text='虛擬試衣使用的模特照片', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_try_ons', to='accounts.photo', verbose_name='模特照片')),
            ],
            options={
                'verbose_name': '虛擬試衣記錄',
                'verbose_name_plural': '虛擬試衣記錄',
                'db_table': 'virtual_try_on',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='virtual_try_on',
            field=models.ForeignKey(blank=True, help_text='此穿搭來自哪個虛擬試衣結果（若為空則是手動建立）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_outfits', to='combine.virtualtryon', verbose_name='虛擬試衣來源'),
        ),
        migrations.CreateModel(
            name='OutfitClothes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_order', models.PositiveIntegerField(default=0, help_text='衣伺在穿搭中的顯示順序', verbose_name='順序')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加時間')),
                ('clothes', models.ForeignKey(help_text='此穿搭包含的衣伺', on_delete=django.db.models.deletion.CASCADE, related_name='outfit_references', to='accounts.clothes', verbose_name='衣伺')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_clothes', to='combine.outfit', verbose_name='穿搭')),
            ],
            options={
                'verbose_name': '穿搭衣伺',
                'verbose_name_plural': '穿搭衣伺',
                'db_table': 'outfit_clothes',
                'ordering': ['position_order'],
                'indexes': [models.Index(fields=['outfit'], name='outfit_clot_outfit__067b39_idx'), models.Index(fields=['clothes'], name='outfit_clot_clothes_7a7a81_idx')],
                'unique_together': {('outfit', 'clothes')},
            },
        ),
        migrations.CreateModel(
            name='OutfitFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('outfit', models.ForeignKey(help_text='被收藏的穿搭', on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='combine.outfit', verbose_name='穿搭')),
                ('user', models.ForeignKey(help_text='收藏此穿搭的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_outfits', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '穿搭收藏',
                'verbose_name_plural': '穿搭收藏',
                'db_table': 'outfit_favorite',
                'indexes': [models.Index(fields=['outfit'], name='outfit_favo_outfit__ba3e26_idx'), models.Index(fields=['user'], name='outfit_favo_user_id_3d5158_idx')],
                'unique_together': {('outfit', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='virtualtryon',
            index=models.Index(fields=['try_on_uid'], name='virtual_try_try_on__b3a6de_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualtryon',
            index=models.Index(fields=['user'], name='virtual_try_user_id_c7a462_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualtryon',
            index=models.Index(fields=['status'], name='virtual_try_status_87c79d_idx'),
        ),
        migrations.AddIndex(
            model_name='virtualtryon',
            index=models.Index(fields=['created_at'], name='virtual_try_created_c15e87_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['outfit_uid'], name='outfit_outfit__552d76_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['created_by'], name='outfit_created_d1a7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['created_at'], name='outfit_created_40ffed_idx'),
        ),
    ]
