# Generated by Django 5.1.5 on 2026-03-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualtryon',
            name='user_photo',
        ),
    ]
