# Generated by Django 5.1.5 on 2026-03-28 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0002_remove_virtualtryon_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(db_column='model_id', primary_key=True, serialize=False)),
                ('f_user_uid', models.CharField(db_column='f_user_uid', help_text='关聯的用戶唯一識別碼', max_length=255, verbose_name='用戶UID')),
                ('model_uid', models.CharField(db_column='model_uid', default=uuid.uuid4, help_text='試穿記錄唯一識別碼', max_length=255, unique=True, verbose_name='模特試穿UID')),
                ('model_picture', models.URLField(blank=True, db_column='model_picture', help_text='衣伺與模特合併後的試穿結果圖片 URL', null=True, verbose_name='試穿結果圖')),
                ('model_style', models.JSONField(blank=True, db_column='model_style', default=list, help_text='AI 分析的穿搭風格陣列', verbose_name='風格分析')),
                ('clothes_list', models.JSONField(blank=True, db_column='clothes_list', default=list, help_text='此試穿包含的 2 件衣伺信息', verbose_name='衣伺清單')),
                ('ai_response_data', models.JSONField(blank=True, db_column='ai_response_data', default=dict, help_text='AI 後端返回的完整 JSON 數據', verbose_name='AI 回應數據')),
                ('model_created_time', models.DateTimeField(auto_now_add=True, db_column='model_created_time', verbose_name='建立時間')),
                ('model_updated_time', models.DateTimeField(auto_now=True, db_column='model_updated_time', verbose_name='更新時間')),
                ('virtual_try_on', models.ForeignKey(blank=True, help_text='此結果來自的虛擬試衣記錄', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_results', to='combine.virtualtryon', verbose_name='虛擬試衣記錄')),
            ],
            options={
                'verbose_name': '模特試穿結果',
                'verbose_name_plural': '模特試穿結果',
                'db_table': 'model',
                'ordering': ['-model_created_time'],
                'indexes': [models.Index(fields=['model_uid'], name='model_model_u_c5cbcf_idx'), models.Index(fields=['f_user_uid'], name='model_f_user__467483_idx'), models.Index(fields=['model_created_time'], name='model_model_c_c9aee7_idx')],
            },
        ),
    ]
