# Generated by Django 6.0.1 on 2026-03-28 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combine', '0004_delete_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', help_text='AI 對此穿搭的分析說明', verbose_name='AI 分析'),
        ),
        migrations.AddField(
            model_name='model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='創建時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='recommendation_context',
            field=models.TextField(blank=True, default='', help_text='用戶的原始推薦請求', verbose_name='推薦背景'),
        ),
        migrations.AddField(
            model_name='model',
            name='recommendation_keywords',
            field=models.JSONField(blank=True, default=dict, help_text='AI 提取的推薦關鍵詞', verbose_name='推薦關鍵詞'),
        ),
        migrations.AddField(
            model_name='model',
            name='recommendation_score',
            field=models.FloatField(default=0.5, help_text='AI 推薦的置信度分數（0.0-1.0）', verbose_name='推薦分數'),
        ),
        migrations.AddField(
            model_name='model',
            name='source',
            field=models.CharField(choices=[('manual', '手動穿搭'), ('ai_recommendation', 'AI 推薦穿搭')], default='manual', help_text='此試穿的來源是手動還是 AI 推薦', max_length=50, verbose_name='來源'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['source'], name='model_source_0154e0_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['f_user_uid', 'created_at'], name='model_f_user__8f50ca_idx'),
        ),
    ]
